### ISSUE TITLE
Instrumenting a function is not working for running process in Dyninst

### ISSUE THREAD

**Issue by ManojKumarChauhan** [dyninst/dyninst#854]
**Intention**
Instrument a counter function into another function of C binary.

**Describe the bug**
Using dyninst 10.1 version with mxz branch . Want to instrument counter function into a C binary's function.
I created a program with bpatch.processAttach and tried to instrument a function. The program got stuck. Same issue can be reproduce in dyninst/parseThat program.

**To Reproduce**
Create any C program which runs infinitely until user close it. Run C binary. Get the process id (pid) of binary.
Go to dyninst/install/bin folder and run parseThat program with following arguments
./parseThat -P pid-of-c-binary  -i 1 -S  path-of-c-binary

parseThat program got stuck when it tries to instrument a function. Got last log
"Inserting counter-increment snippet into function entry"

**Expected behavior**
 parseThat program should not stuck and it should instrument the function into C binary successfully.

**System (please complete the following information):**
 -ubuntu 16.04 x86_64

**Additional context**
Issue is reproducing for version 10.1. Program crashed for old dyninst versions like 8.2.

**Comment by mxz297** [comment]
It is not clear to me whether there is a problem or not. `parseThat` will wait for the mutatee to finish. However, since your mutatee runs infinitely, `parseThat` will also runs infinitely. Below is the infinite loop in `parseThat` that waits for the completion of the mutatee.

https://github.com/dyninst/dyninst/blob/master/parseThat/src/dyninstCore.C#L577

Additional comments:

1. Can you check if 10.2 has the same problem? 
2. We appreciate your bug report. It is extremely helpful to provide complete bug reproducers, even if your reproducer may contain just a few lines of code. It is also use to include compilation commands or makefile so that we can compile your reproducer in the same way as you do.

**Comment by mxz297** [comment]
You can also verify where `parseThat` stuck by using gdb to attach the `parseThat` process and get a stack trace. That can also be helpful for determining what's going on.

**Comment by ManojKumarChauhan** [comment]
C program is running a thread where the thread is doing some work after say every 2 seconds of interval.
I will try that in 10.2. In case if the issue still exists then I will provide all the required information to reproduce it. I am using mxz branch because it contains the fix for golang. Have you also merged golang changes in 10.2? Because there may be a big difference between both the branches so could you please suggest the best way.

**Comment by mxz297** [comment]
My branch is not in Dyninst 10.2. It will take quite some time before my branch can be merged into dyninst mainstream. If 10.2 resolves your problem, I will just update my branch on top of 10.2.

**Comment by ManojKumarChauhan** [comment]
Yes the problem is fixed in 10.2.

**Comment by ManojKumarChauhan** [comment]
Hi @mxz297 ,
Are you planning to merge 10.2 changes in your branch (layout_opt) ? OR you will merge your branch in 10.2 which will take some time?

**Comment by ManojKumarChauhan** [comment]
closing this as it's working fine in 10.2

**Comment by mxz297** [comment]
> Hi @mxz297 ,
> Are you planning to merge 10.2 changes in your branch (layout_opt) ? OR you will merge your branch in 10.2 which will take some time?

Sorry. I was waiting for some experiments to finish before I can upgrade my branch to 10.2. I will merge 10.2 to my branch later today.

**Comment by ManojKumarChauhan** [comment]
Thanks @mxz297 ,
Getting compilation errors in branch layout_opt.

[  3%] Building CXX object common/CMakeFiles/common.dir/src/arch-x86.C.o
In file included from /usr/include/c++/5/bits/hashtable.h:35:0,
                 from /usr/include/c++/5/unordered_set:47,
                 from /opt/temp/dyninst/common/h/dyntypes.h:56,
                 from /opt/temp/dyninst/common/src/Types.h:138,
                 from /opt/temp/dyninst/common/src/arch-x86.C:135:
/usr/include/c++/5/bits/hashtable_policy.h: In instantiation of ‘struct std::__detail::__is_noexcept_hash<entryID, std::hash<entryID> >’:
/usr/include/c++/5/type_traits:137:12:   required from ‘struct std::__and_<std::__is_fast_hash<std::hash<entryID> >, std::__detail::__is_noexcept_hash<entryID, std::hash<entryID> > >’
/usr/include/c++/5/type_traits:148:38:   required from ‘struct std::__not_<std::__and_<std::__is_fast_hash<std::hash<entryID> >, std::__detail::__is_noexcept_hash<entryID, std::hash<entryID> > > >’
/usr/include/c++/5/bits/unordered_map.h:100:66:   required from ‘class std::unordered_map<entryID, std::__cxx11::basic_string<char>, std::hash<entryID>, std::equal_to<entryID>, std::allocator<std::pair<const entryID, std::__cxx11::basic_string<char> > > >’
/opt/temp/dyninst/common/src/arch-x86.C:868:50:   required from here
/usr/include/c++/5/bits/hashtable_policy.h:85:34: error: no match for call to ‘(const std::hash<entryID>) (const entryID&)’
  noexcept(declval<const _Hash&>()(declval<const _Key&>()))>
                                  ^
In file included from /usr/include/c++/5/bits/move.h:57:0,
                 from /usr/include/c++/5/bits/stl_pair.h:59,
                 from /usr/include/c++/5/utility:70,
                 from /usr/include/c++/5/tuple:38,
                 from /usr/include/c++/5/mutex:38,
                 from /opt/temp/dyninst/common/src/vgannotations.h:60,
                 from /opt/temp/dyninst/common/src/arch-x86.C:132:
/usr/include/c++/5/type_traits: In instantiation of ‘struct std::__not_<std::__and_<std::__is_fast_hash<std::hash<entryID> >, std::__detail::__is_noexcept_hash<entryID, std::hash<entryID> > > >’:
/usr/include/c++/5/bits/unordered_map.h:100:66:   required from ‘class std::unordered_map<entryID, std::__cxx11::basic_string<char>, std::hash<entryID>, std::equal_to<entryID>, std::allocator<std::pair<const entryID, std::__cxx11::basic_string<char> > > >’
/opt/temp/dyninst/common/src/arch-x86.C:868:50:   required from here
/usr/include/c++/5/type_traits:148:38: error: ‘value’ is not a member of ‘std::__and_<std::__is_fast_hash<std::hash<entryID> >, std::__detail::__is_noexcept_hash<entryID, std::hash<entryID> > >’
     : public integral_constant<bool, !_Pp::value>

Latest code in master branch is also giving some errors.
