### ISSUE TITLE
dyninstAPI_RT build failure on Windows

### ISSUE THREAD

**Issue by pefoley2** [dyninst/dyninst#92]
Introduced by https://github.com/dyninst/dyninst/commit/ce99292ae64edc87665ea5de19a6036fa376ac0d

1>  RTheap.c
1>C:\Users\Peter\Source\Repos\dyninst\dyninstAPI_RT\src\RTheap.c(286): warning C4047: '=': 'heapList_t *' differs in levels of indirection from 'Address'
1>C:\Users\Peter\Source\Repos\dyninst\dyninstAPI_RT\src\RTheap.c(294): warning C4047: 'function': 'Address' differs in levels of indirection from 'void *'
1>C:\Users\Peter\Source\Repos\dyninst\dyninstAPI_RT\src\RTheap.c(294): warning C4024: 'heap_alignUp': different types for formal and actual parameter 1
1>C:\Users\Peter\Source\Repos\dyninst\dyninstAPI_RT\src\RTheap.c(296): warning C4047: '=': 'void *' differs in levels of indirection from 'Address'
1>C:\Users\Peter\Source\Repos\dyninst\dyninstAPI_RT\src\RTheap.c(298): error C2036: 'void *': unknown size

**Comment by wrwilliams** [comment]
Should be safe to declare heap as an address in DYNINSTos_malloc, rather than as a void*, which will make the pointer math behave.

**Comment by wrwilliams** [comment]
Fixed by #108, which was incorporated into #107.
