### ISSUE TITLE
test1_30 test failure

### ISSUE THREAD

**Issue by mcfadden8** [dyninst/dyninst#281]
Is anyone else seeing problems with test1_30?

I am seeing the following test failure from https://github.com/dyninst/dyninst/commit/d2f0f1051e5caf605471fa19532334fcce9bb508

```
$ ./runTests -test test1_30 -log lfile
*** Child terminated abnormally via signal 11.
test1_30                   g++    none 64  create   NA      dynamic nonPIC  CRASHED (Running Test)
*** Child terminated abnormally via signal 11.
test1_30                   g++    none 64  rewriter NA      dynamic nonPIC  CRASHED (Running Test)

$ cat lfile
Commencing test(s) ...
Wed Nov 30 11:58:31 PST 2016
Linux rzhasgpu6 2.6.32-642.6.2.1chaos.ch5.5.x86_64 #1 SMP Mon Oct 24 10:49:01 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
TESTDIR=/g/g0/martymcf/cuda/install/x86_64/bin/testsuite
[Tests with dyninst_group_test.dyn_g++_64_none_none]
-rwxr-xr-x 1 martymcf martymcf 197036 Nov 29 14:53 dyninst_group_test.dyn_g++_64_none_none*
        linux-vdso.so.1 =>  (0x00002aaaaaacb000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00002aaaaacce000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00002aaaaaed3000)
        libm.so.6 => /lib64/libm.so.6 (0x00002aaaab1d9000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00002aaaab45d000)
        libc.so.6 => /lib64/libc.so.6 (0x00002aaaab674000)
        /lib64/ld-linux-x86-64.so.2 (0x00002aaaaaaab000)

Commencing test(s) ...
Wed Nov 30 11:58:45 PST 2016
Linux rzhasgpu6 2.6.32-642.6.2.1chaos.ch5.5.x86_64 #1 SMP Mon Oct 24 10:49:01 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
TESTDIR=/g/g0/martymcf/cuda/install/x86_64/bin/testsuite
[Tests with dyninst_group_test.dyn_g++_64_none_none]
-rwxr-xr-x 1 martymcf martymcf 197036 Nov 29 14:53 dyninst_group_test.dyn_g++_64_none_none*
        linux-vdso.so.1 =>  (0x00002aaaaaacb000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00002aaaaacce000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00002aaaaaed3000)
        libm.so.6 => /lib64/libm.so.6 (0x00002aaaab1d9000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00002aaaab45d000)
        libc.so.6 => /lib64/libc.so.6 (0x00002aaaab674000)
        /lib64/ld-linux-x86-64.so.2 (0x00002aaaaaaab000)

[Tests with dyninst_group_test.dyn_g++_64_none_none]
-rwxr-xr-x 1 martymcf martymcf 197036 Nov 29 14:53 dyninst_group_test.dyn_g++_64_none_none*
        linux-vdso.so.1 =>  (0x00002aaaaaacb000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00002aaaaacce000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00002aaaaaed3000)
        libm.so.6 => /lib64/libm.so.6 (0x00002aaaab1d9000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00002aaaab45d000)
        libc.so.6 => /lib64/libc.so.6 (0x00002aaaab674000)
        /lib64/ld-linux-x86-64.so.2 (0x00002aaaaaaab000)

Commencing test(s) ...
Wed Nov 30 11:58:49 PST 2016
Linux rzhasgpu6 2.6.32-642.6.2.1chaos.ch5.5.x86_64 #1 SMP Mon Oct 24 10:49:01 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
TESTDIR=/g/g0/martymcf/cuda/install/x86_64/bin/testsuite
[Tests with dyninst_group_test.dyn_g++_64_none_none]
-rwxr-xr-x 1 martymcf martymcf 197036 Nov 29 14:53 dyninst_group_test.dyn_g++_64_none_none*
        linux-vdso.so.1 =>  (0x00002aaaaaacb000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00002aaaaacce000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00002aaaaaed3000)
        libm.so.6 => /lib64/libm.so.6 (0x00002aaaab1d9000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00002aaaab45d000)
        libc.so.6 => /lib64/libc.so.6 (0x00002aaaab674000)
        /lib64/ld-linux-x86-64.so.2 (0x00002aaaaaaab000)
```

Gdb of the core file gives results that don't seem to be helpful:
```
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00002aaaac958d1d in __libc_start_main (main=0x40656a <main(int, char**)>, argc=7, ubp_av=0x7fffffffcbe8, 
    init=<value optimized out>, fini=<value optimized out>, rtld_fini=<value optimized out>, stack_end=0x7fffffffcbd8)
    at libc-start.c:226
#2  0x0000000000406179 in _start ()
(gdb) 
```
Please let me know if there is additional information needed.

**Comment by wrwilliams** [comment]
I'm not seeing anything like this with dynamically linked binaries on RHEL6/x86_64, and I don't think anyone else at UW is either (@ssunny7 and @jdetter I know have Ubuntu14 systems, and @mxz297 has RHEL7). Statically linked binaries are misbehaving for some of us though.

Is this equivalent to a CZ x86-64 system I can use for reproduction?

**Comment by ssunny7** [comment]
I tried this on my machine. I'm getting similar results:

`Commencing test(s) ...
Thu Dec  1 12:04:33 CST 2016
Linux bigking 4.4.0-45-generic #66~14.04.1-Ubuntu SMP Wed Oct 19 15:05:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
TESTDIR=/afs/cs.wisc.edu/p/paradyn/development/ssunny/dyninst/testsuite-install/bin/testsuite
[Tests with dyninst_group_test.dyn_g++_64_none_none]
-rwxr-xr-x 1 ssunny ssunny 270574 Nov 30 18:07 dyninst_group_test.dyn_g++_64_none_none*
        linux-vdso.so.1 =>  (0x00007ffc77707000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fca2a9f8000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fca2a632000)
        /lib64/ld-linux-x86-64.so.2 (0x000055a000c46000)

Passed test #30 (line information)
All tests passed.
Commencing test(s) ...
Thu Dec  1 12:04:38 CST 2016
Linux bigking 4.4.0-45-generic #66~14.04.1-Ubuntu SMP Wed Oct 19 15:05:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
TESTDIR=/afs/cs.wisc.edu/p/paradyn/development/ssunny/dyninst/testsuite-install/bin/testsuite
[Tests with dyninst_group_test.dyn_g++_64_none_none]
-rwxr-xr-x 1 ssunny ssunny 270574 Nov 30 18:07 dyninst_group_test.dyn_g++_64_none_none*
        linux-vdso.so.1 =>  (0x00007ffd7e9d3000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdbe5e60000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdbe5a9a000)
        /lib64/ld-linux-x86-64.so.2 (0x0000563cbd90d000)

[Tests with dyninst_group_test.dyn_g++_64_none_none]
-rwxr-xr-x 1 ssunny ssunny 270574 Nov 30 18:07 dyninst_group_test.dyn_g++_64_none_none*
        linux-vdso.so.1 =>  (0x00007ffdd8193000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa16b78d000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa16b3c7000)
        /lib64/ld-linux-x86-64.so.2 (0x00005629ed693000)

Commencing test(s) ...
Thu Dec  1 12:04:40 CST 2016
Linux bigking 4.4.0-45-generic #66~14.04.1-Ubuntu SMP Wed Oct 19 15:05:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
TESTDIR=/afs/cs.wisc.edu/p/paradyn/development/ssunny/dyninst/testsuite-install/bin/testsuite
[Tests with dyninst_group_test.dyn_g++_64_none_none]
-rwxr-xr-x 1 ssunny ssunny 270574 Nov 30 18:07 dyninst_group_test.dyn_g++_64_none_none*
        linux-vdso.so.1 =>  (0x00007ffc2419e000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f04491ea000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0448e24000)
        /lib64/ld-linux-x86-64.so.2 (0x0000555c9244e000)`.

**Comment by wrwilliams** [comment]
Can you get a quick stack trace for this one, Sunny? test_driver under gdb should be well-behaved here.

**Comment by ssunny7** [comment]
So if I run just this test with `test_driver`, I directly get a seg fault without it printing pass/fail results. Loading this in `gdb` gives the following trace from `bt`:

```
#0  Dyninst::SymtabAPI::LineInformation::equal_range (this=this@entry=0xc64f4a0, file="test1_30_mutatee.c", lineNo=lineNo@entry=80)
    at /u/s/s/ssunny/dev-home/dyninst/dyninst-code/symtabAPI/src/LineInformation.C:218
#1  0x00007ffff4275175 in Dyninst::SymtabAPI::LineInformation::getAddressRanges (this=0xc64f4a0, lineSource=<optimized out>, lineNo=lineNo@entry=80, ranges=std::vector of length 0, capacity 0)
    at /u/s/s/ssunny/dev-home/dyninst/dyninst-code/symtabAPI/src/LineInformation.C:141
#2  0x00007ffff42a11fa in Dyninst::SymtabAPI::Module::getAddressRanges (this=<optimized out>, ranges=std::vector of length 0, capacity 0, lineSource="test1_30_mutatee.c", lineNo=lineNo@entry=80)
    at /u/s/s/ssunny/dev-home/dyninst/dyninst-code/symtabAPI/src/Module.C:151
#3  0x00007ffff5c310e4 in BPatch_module::getAddressRanges (this=0xc58d250, fileName=<optimized out>, fileName@entry=0x7ffff2966de7 "test1_30_mutatee.c", lineNo=lineNo@entry=80, 
    ranges=std::vector of length 0, capacity 0) at /u/s/s/ssunny/dev-home/dyninst/dyninst-code/dyninstAPI/src/BPatch_module.C:744
#4  0x00007ffff5c181c6 in BPatch_image::getAddressRanges (this=<optimized out>, lineSource=0x7ffff2966de7 "test1_30_mutatee.c", lineNo=80, ranges=std::vector of length 0, capacity 0)
    at /u/s/s/ssunny/dev-home/dyninst/dyninst-code/dyninstAPI/src/BPatch_image.C:903
#5  0x00007ffff2965aa7 in test1_30_Mutator::executeTest() () from ./libtest1_30.so
#6  0x0000000000412fb9 in executeTest(ComponentTester*, RunGroup*, TestInfo*, std::map<std::string, Parameter*, std::less<std::string>, std::allocator<std::pair<std::string const, Parameter*> > >)
    ()
#7  0x000000000041498c in executeGroup(RunGroup*, std::vector<RunGroup*, std::allocator<RunGroup*> >&, std::map<std::string, Parameter*, std::less<std::string>, std::allocator<std::pair<std::string const, Parameter*> > >&) ()
#8  0x00000000004156e5 in startAllTests(std::vector<RunGroup*, std::allocator<RunGroup*> >&, std::map<std::string, Parameter*, std::less<std::string>, std::allocator<std::pair<std::string const, Parameter*> > >&) ()
#9  0x0000000000416394 in main ()
```
Also, the seg fault is shown to be at
```
Program received signal SIGSEGV, Segmentation fault.
Dyninst::SymtabAPI::LineInformation::equal_range (this=this@entry=0xc64f4a0, file="test1_30_mutatee.c", lineNo=lineNo@entry=80)
    at /u/s/s/ssunny/dev-home/dyninst/dyninst-code/symtabAPI/src/LineInformation.C:218
218	    while((*bounds.first)->getLine() < lineNo && bounds.first != bounds.second) {
```

If I run only `test1_30` with `runTests`, I don't get a seg fault and I do get the pass/fail output. But loading this in `gdb` gives `No stack` after running `bt`.

**Comment by mcfadden8** [comment]
Hi @wrwilliams,

I thought you had access to machines on the RZ.  Is this not the case?  I also notice the @ssunny7 is able to reproduce this as well in his environment.  Let me know if you still need for me to find a configuration in the CZ.

**Comment by wrwilliams** [comment]
I think rzuseq is the only RZ system I have access to, which is no good for reproducing x86 bugs. :)

@ssunny7 has provided confirmation that this is a problem I've got a local fix for, though, and those fixes are coming up soon, so it should be moot as long as your backtrace matches his.

**Comment by wrwilliams** [comment]
Should be fixed on master. @mcfadden8 can you close this when you have a chance to verify that's true for you as well as for Jenkins?

**Comment by mcfadden8** [comment]
I grabbed the latest but it am seeing compilation errors:

```
[ 17%] Building CXX object symtabAPI/CMakeFiles/symtabAPI.dir/src/Object-elf.C.o
/g/g0/martymcf/dyninst/src/dyninst/symtabAPI/src/Object-elf.C: In member function 'virtual void Dyninst::SymtabAPI::Object::parseLineInfoForCU(Dwarf_Die_s*, Dyninst::SymtabAPI::LineInformation*)':
/g/g0/martymcf/dyninst/src/dyninst/symtabAPI/src/Object-elf.C:4325: error: template argument for 'template<class _Alloc> class std::allocator' uses local type 'Dyninst::SymtabAPI::Object::parseLineInfoForCU(Dwarf_Die_s*, Dyninst::SymtabAPI::LineInformation*)::open_statement'
/g/g0/martymcf/dyninst/src/dyninst/symtabAPI/src/Object-elf.C:4325: error:   trying to instantiate 'template<class _Alloc> class std::allocator'
/g/g0/martymcf/dyninst/src/dyninst/symtabAPI/src/Object-elf.C:4325: error: template argument 2 is invalid
/g/g0/martymcf/dyninst/src/dyninst/symtabAPI/src/Object-elf.C:4325: error: invalid type in declaration before ';' token
/g/g0/martymcf/dyninst/src/dyninst/symtabAPI/src/Object-elf.C:4438: error: template argument for 'template<class _Alloc> class std::allocator' uses local type 'Dyninst::SymtabAPI::Object::parseLineInfoForCU(Dwarf_Die_s*, Dyninst::SymtabAPI::LineInformation*)::open_statement'
/g/g0/martymcf/dyninst/src/dyninst/symtabAPI/src/Object-elf.C:4438: error:   trying to instantiate 'template<class _Alloc> class std::allocator'
/g/g0/martymcf/dyninst/src/dyninst/symtabAPI/src/Object-elf.C:4438: error: template argument 2 is invalid
/g/g0/martymcf/dyninst/src/dyninst/symtabAPI/src/Object-elf.C:4438: error: invalid type in declaration before ';' token
/g/g0/martymcf/dyninst/src/dyninst/symtabAPI/src/Object-elf.C:4439: error: request for member 'begin' in 'open_statements', which is of non-class type 'int'
/g/g0/martymcf/dyninst/src/dyninst/symtabAPI/src/Object-elf.C:4439: error: unable to deduce 'auto' from '<expression error>'
/g/g0/martymcf/dyninst/src/dyninst/symtabAPI/src/Object-elf.C:4440: error: request for member 'end' in 'open_statements', which is of non-class type 'int'
/g/g0/martymcf/dyninst/src/dyninst/symtabAPI/src/Object-elf.C:4456: error: request for member 'push_back' in 'tmp', which is of non-class type 'int'
/g/g0/martymcf/dyninst/src/dyninst/symtabAPI/src/Object-elf.C:4459: error: request for member 'swap' in 'open_statements', which is of non-class type 'int'
/g/g0/martymcf/dyninst/src/dyninst/symtabAPI/src/Object-elf.C:4461: error: request for member 'clear' in 'open_statements', which is of non-class type 'int'
/g/g0/martymcf/dyninst/src/dyninst/symtabAPI/src/Object-elf.C:4464: error: request for member 'push_back' in 'open_statements', which is of non-class type 'int'
/g/g0/martymcf/dyninst/src/dyninst/symtabAPI/src/Object-elf.C:4467: error: request for member 'begin' in 'open_statements', which is of non-class type 'int'
/g/g0/martymcf/dyninst/src/dyninst/symtabAPI/src/Object-elf.C:4467: error: unable to deduce 'auto' from '<expression error>'
/g/g0/martymcf/dyninst/src/dyninst/symtabAPI/src/Object-elf.C:4468: error: request for member 'end' in 'open_statements', which is of non-class type 'int'
/g/g0/martymcf/dyninst/src/dyninst/symtabAPI/src/Object-elf.C:4378: warning: unused variable 'isPreviousValid'
/g/g0/martymcf/dyninst/src/dyninst/symtabAPI/src/Object-elf.C:4384: warning: unused variable 'needs_followup'
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-unused-local-typedefs"
make[2]: *** [symtabAPI/CMakeFiles/symtabAPI.dir/src/Object-elf.C.o] Error 1
make[1]: *** [symtabAPI/CMakeFiles/symtabAPI.dir/all] Error 2
make: *** [all] Error 2

**Comment by wrwilliams** [comment]
...wow, 4.4 doesn't support internal classes? I can pull that struct definition out ahead of the function (and will), but 4.4 is getting old and busted in a pretty serious way. Is 4.8 readily available on most chaos systems?

**Comment by mcfadden8** [comment]
I tried to compile with gcc4.8.5 and am getting the following linkage errors:

```
$ make
[  0%] Building DyninstRT
[ 50%] Built target dyninstAPI_RT
[100%] Built target dyninstAPI_RT_static
[  0%] Built target DyninstRT
Linking CXX shared library libcommon.so
/collab/usr/gapps/opnsrc/gnu/dev/lnx-2.12-o/4.8.5/x86_64-unknown-linux-gnu/bin/ld.raw: /collab/usr/gapps/opnsrc/gnu/dev/lnx-2.12-o/4.8.5/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../lib64/libiberty.a(cplus-dem.o): relocation R_X86_64_32S against `_sch_istable' can not be used when making a shared object; recompile with -fPIC
/collab/usr/gapps/opnsrc/gnu/dev/lnx-2.12-o/4.8.5/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../lib64/libiberty.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [common/libcommon.so.9.2.0] Error 1
make[1]: *** [common/CMakeFiles/common.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by wrwilliams** [comment]
Yep, that's a non-PIC statically linked binutils. I think if you flip the CMake `USE_GNU_DEMANGLER` option it'll work around that bit of fail, or you can go back to 4.4 and move the `open_statements` struct out ahead of `parse_line_info_for_CU` and it should behave.

I'm arguing with a few other papercuts on master but should have a fix for `open_statements` among others pushed up soon.

**Comment by mcfadden8** [comment]
Okay, I'll wait.

**Comment by wrwilliams** [comment]
Merged now; let me know how it goes.

**Comment by mcfadden8** [comment]
Looks pretty good!  I am seeing one strange thing however:

```
$ ./runTests -all -test test1_30           
test1_30                   g++    none 64  create   NA      dynamic nonPIC  PASSED
test1_30                   g++    none 64  attach   NA      dynamic nonPIC  PASSED
test1_30                   g++    none 64  rewriter NA      dynamic nonPIC  PASSED
test1_30                   g++    none 64  create   NA      dynamic PIC     PASSED
test1_30                   g++    none 64  attach   NA      dynamic PIC     PASSED
test1_30                   g++    none 64  rewriter NA      dynamic PIC     PASSED
test1_30                   gcc    none 64  create   NA      dynamic nonPIC  PASSED
test1_30                   gcc    none 64  attach   NA      dynamic nonPIC  PASSED
test1_30                   gcc    none 64  rewriter NA      dynamic nonPIC  PASSED
test1_30                   gcc    none 64  create   NA      dynamic PIC     PASSED
test1_30                   gcc    none 64  attach   NA      dynamic PIC     PASSED
test1_30                   gcc    none 64  rewriter NA      dynamic PIC     PASSED
test1_30                   icc    none 64  create   NA      dynamic nonPIC  PASSED
test1_30                   icc    none 64  attach   NA      dynamic nonPIC  PASSED
test1_30                   icc    none 64  rewriter NA      dynamic nonPIC  PASSED
test1_30                   icc    none 64  create   NA      dynamic PIC     PASSED
test1_30                   icc    none 64  attach   NA      dynamic PIC     PASSED
test1_30                   icc    none 64  rewriter NA      dynamic PIC     PASSED
test1_30                   icpc   none 64  create   NA      dynamic nonPIC  PASSED
test1_30                   icpc   none 64  attach   NA      dynamic nonPIC  PASSED
test1_30                   icpc   none 64  rewriter NA      dynamic nonPIC  PASSED
test1_30                   icpc   none 64  create   NA      dynamic PIC     PASSED
test1_30                   icpc   none 64  attach   NA      dynamic PIC     PASSED
test1_30                   icpc   none 64  rewriter NA      dynamic PIC     PASSED
test1_30                   pgcc   none 64  create   NA      dynamic nonPIC  PASSED
test1_30                   pgcc   none 64  attach   NA      dynamic nonPIC  PASSED
test1_30                   pgcc   none 64  rewriter NA      dynamic nonPIC  PASSED
test1_30                   pgcc   none 64  create   NA      dynamic PIC     PASSED
test1_30                   pgcc   none 64  attach   NA      dynamic PIC     PASSED
test1_30                   pgcc   none 64  rewriter NA      dynamic PIC     PASSED
test1_30                   pgcxx  none 64  create   NA      dynamic nonPIC  PASSED
test1_30                   pgcxx  none 64  attach   NA      dynamic nonPIC  PASSED
test1_30                   pgcxx  none 64  rewriter NA      dynamic nonPIC  PASSED
test1_30                   pgcxx  none 64  create   NA      dynamic PIC     PASSED
test1_30                   pgcxx  none 64  attach   NA      dynamic PIC     PASSED
test1_30                   pgcxx  none 64  rewriter NA      dynamic PIC     PASSED
Invocation of routine at SymtabCodeSource.C:635 is ambiguous for binaries with overlapping code regions
Invocation of routine at SymtabCodeSource.C:635 is ambiguous for binaries with overlapping code regions
Invocation of routine at SymtabCodeSource.C:635 is ambiguous for binaries with overlapping code regions
Invocation of routine at SymtabCodeSource.C:696 is ambiguous for binaries with overlapping code regions
Invocation of routine at SymtabCodeSource.C:696 is ambiguous for binaries with overlapping code regions
Invocation of routine at SymtabCodeSource.C:635 is ambiguous for binaries with overlapping code regions
Invocation of routine at SymtabCodeSource.C:696 is ambiguous for binaries with overlapping code regions
Invocation of routine at SymtabCodeSource.C:635 is ambiguous for binaries with overlapping code regions
Invocation of routine at SymtabCodeSource.C:696 is ambiguous for binaries with overlapping code regions
Invocation of routine at SymtabCodeSource.C:635 is ambiguous for binaries with overlapping code regions
Invocation of routine at SymtabCodeSource.C:696 is ambiguous for binaries with overlapping code regions
Invocation of routine at SymtabCodeSource.C:635 is ambiguous for binaries with overlapping code regions
Invocation of routine at SymtabCodeSource.C:696 is ambiguous for binaries with overlapping code regions
Invocation of routine at SymtabCodeSource.C:635 is ambiguous for binaries with overlapping code regions
Invocation of routine at SymtabCodeSource.C:696 is ambiguous for binaries with overlapping code regions
Invocation of routine at SymtabCodeSource.C:635 is ambiguous for binaries with overlapping code regions
Invocation of routine at SymtabCodeSource.C:696 is ambiguous for binaries with overlapping code regions
Invocation of routine at SymtabCodeSource.C:635 is ambiguous for binaries with overlapping code regions
Invocation of routine at SymtabCodeSource.C:671 is ambiguous for binaries with overlapping code regions
Invocation of routine at SymtabCodeSource.C:696 is ambiguous for binaries with overlapping code regions
Invocation of routine at SymtabCodeSource.C:671 is ambiguous for binaries with overlapping code regions
Invocation of routine at SymtabCodeSource.C:696 is ambiguous for binaries with overlapping code regions
Invocation of routine at SymtabCodeSource.C:635 is ambiguous for binaries with overlapping code regions
Invocation of routine at SymtabCodeSource.C:671 is ambiguous for binaries with overlapping code regions
Invocation of routine at SymtabCodeSource.C:671 is ambiguous for binaries with overlapping code regions
...
...
test1_30                   g++    none 64  rewriter NA      static  nonPIC  PASSED
test1_30                   g++    none 64  rewriter NA      static  PIC     PASSED
test1_30                   gcc    none 64  rewriter NA      static  nonPIC  PASSED
test1_30                   gcc    none 64  rewriter NA      static  PIC     PASSED
```

**Comment by wrwilliams** [comment]
That's normal, though it could stand to be quieter (and could use a bit of attention). Statically linked binaries get "overlapping" code regions when there's a zero-size section that's at the same nominal offset as .text, and in the case where there's more than one non-zero-size region, SymtabCodeSource can get confused. We're fine here though.

**Comment by jdetter** [comment]
Did this get merged into master?

**Comment by wrwilliams** [comment]
Yes.

**Comment by jdetter** [comment]
@wrwilliams Ok to close?

**Comment by wrwilliams** [comment]
Yeah
