### ISSUE TITLE
getABIVersion() not defined in Object-nt.h

### ISSUE THREAD

**Issue by pefoley2** [dyninst/dyninst#21]
Broken by https://github.com/dyninst/dyninst/commit/6dd97f53de96d9bbe38f23626c84811624d0d74e
getABIVersion() is only implemented for elf objects.

**Comment by mcfadden8** [comment]
Argh.  I renamed the method and forgot to change the virtual one in Object.h.  Patch is here: [https://github.com/dyninst/dyninst/pull/24](https://github.com/dyninst/dyninst/pull/24)

Unfortunately, I do not have a Windows machine to test this.  Can someone try it to make sure it works?

**Comment by pefoley2** [comment]
https://ci.appveyor.com/project/wrwilliams/dyninst/build/1.0.6 shold let you know if the fix compiles properly.

**Comment by mcfadden8** [comment]
Please do not merge this patch yet.  I have discovered some (PPC64LE) proccontrol test problems and I need to determine whether it is related to this change or to others that have gone in to the tree.

**Comment by pefoley2** [comment]
I'm assuming you mean this error?
[  6%] Building CXX object CMakeFiles/testproccontrol.dir/src/proccontrol/proccontrol_comp.C.o
/home/peter/testsuite/src/proccontrol/proccontrol_comp.C: In member function ‘uint64_t ProcControlComponent::adjustFunctionEntryAddress(Dyninst::ProcControlAPI::Process::const_ptr, uint64_t)’:
/home/peter/testsuite/src/proccontrol/proccontrol_comp.C:343:16: error: ‘class Dyninst::SymReader’ has no member named ‘getABIVersion’
       if (rdr->getABIVersion(major, minor)) {
